---
title: "R_final"
author: "2021710121_신기성"
date: '2022-05-30'
output: 
  html_document: 
    toc: yes
    highlight: textmate
    theme: cosmo
    toc_depth : 3
    toc_float : yes
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
install.packages("data.table", repos = "http://cran.us.r-project.org")
library(data.table)

install.packages("jstable", repos = "http://cran.us.r-project.org")
library(jstable)

```

## Table 1 만들기
아래처럼 데이터를 읽은 후, Q_로 시작하는 변수를 범주형으로 바꾼 후, 연도별 기술통계량을 Table로 나타내어라 (jstable::CreateTableOnesJS 이용)

```{r cars}

a <- fread("https://raw.githubusercontent.com/jinseob2kim/lecture-snuhlab/master/data/example_g1e.csv")
vars.factor <- grep("Q_", names(a), value = T )

for (v in vars.factor) {
  a[[v]] <- factor(a[[v]])
}


vars.tb1 <- names(a)[-c(1:3)]

tb1 <- CreateTableOneJS(vars = vars.tb1, strata = "EXMD_BZ_YYYY", data = a)
#knitr::kable(tb1$table, caption = tb1$caption)

install.packages("DT", repos = "http://cran.us.r-project.org")
DT::datatable(tb1$table)  
```

## 회귀분석

### 선형회귀분석

time ~ rx + age + sex 선형회귀 실행 후 table로 나타내어라

```{r}
library(survival)
#colon
res.reg <- glm(time ~ rx + age + sex, data = colon)

tb.reg <- glmshow.display(res.reg)

knitr::kable(tb.reg$table, caption = tb.reg$first.line)

```


### 로지스틱
status ~ rx + age + sex 로지스틱회귀 실행 후 Table로 나타내어라

```{r}
library(survival)
#colon
res.logistic <- glm(status ~ rx + age + sex, data = colon, family = binomial)

tb.logistic <-glmshow.display(res.logistic)
knitr::kable(tb.logistic$table, caption = tb.logistic$first.line)
```


### 생존분석

#### Cox
Surv(time, status) ~ rx + age + sex 실행 후 Table로 나타내어라(jstable::cox2.display 이용)

```{r}
library(survival)
res.cox <- coxph(Surv(time, status) ~ rx + age + sex, data = colon, model = T)
tb.cox <- cox2.display(res.cox)
knitr::kable(tb.cox$table, caption = tb.cox$caption)
```



#### Kaplan-meier

Surv(time, status) ~ rx 실행 후 그림으로 나타내어라 (jskm::jskm 이용)

```{r}
install.packages("jskm", repos = "http://cran.us.r-project.org")
library(jskm)

res.km <- survfit(Surv(time, status) ~ rx, data = colon)

jskm::jskm(res.km, table = T, pval = T, label.nrisk = "No. at risk", size.label.nrisk = 0,
           xlabs = "Time(Day)", ylabs = "Survival", ystratalabs = c("Obs", "Lev", "Lev + 5FU"), ystrataname = "rx",
           marks = F, timeby = 365, xlims = c(0, 3000), ylims = c(0.25, 1), showpercent = T)
```
